name: Deploy Modul Timbangan App to cPanel

on:
  push:
    branches:
      - main # Atau branch yang Anda gunakan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOSTNAME }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /home/u1563753/public_html/timbangan.curaweda.com # Ganti dengan path direktori di cPanel Anda
